export const INPUT_WITH_TEXT_REQUIRED = 'INPUT_WITH_TEXT_REQUIRED';
export const INPUT_WITH_NUMBERS_REQUIRED = 'INPUT_WITH_NUMBERS_REQUIRED';
export const INPUT_WITH_MIN_LENGTH_REQUIRED = 'INPUT_WITH_MIN_LENGTH_REQUIRED';
export const INPUT_WITH_MAX_LENGTH_REQUIRED = 'INPUT_WITH_MAX_LENGTH_REQUIRED';

export const INPUT_WITH_CARD_NUMBER = 'INPUT_WITH_CARD_NUMBER';
export const INPUT_WITH_EMAIL = 'INPUT_WITH_EMAIL';
export const INPUT_WITH_PHONE_NUMBER = 'INPUT_WITH_PHONE_NUMBER';
